name: Tracker-Discord

on:
    issue_comment:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Issue Track
            - uses: iamsaquib/tracker-discord@master
